spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/@database.name@?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
    username: '@database.username@'
    password: '@database.password@'
  jpa:
    properties:
      hibernate.format_sql: true
      # Default is fault, turn on for debugging 
      #hibernate.show_sql: true
  main.banner-mode: 'off'
